export const initializeDateState = () => ({
  turningOverDate: null,
  turningOverAndOverDate: null,
  crawlingDate: null,
  sittingDate: null,
  crawlingOnHandAndKneesDate: null,
  pullingUpToStandDate: null,
  cruisingDate: null,
  standingDate: null,
  walkingDate: null,
  turningOverCompDate: null,
  turningOverAndOverCompDate: null,
  crawlingCompDate: null,
  sittingCompDate: null,
  crawlingOnHandAndKneesCompDate: null,
  pullingUpToStandCompDate: null,
  cruisingCompDate: null,
  standingCompDate: null,
  walkingCompDate: null,
});
