export const initializeState = () => ({
  turningOver: false,
  turningOverAndOver: false,
  crawling: false,
  sitting: false,
  crawlingOnHandAndKnees: false,
  pullingUpToStand: false,
  cruising: false,
  standing: false,
  walking: false,
  turningOverComp: false,
  turningOverAndOverComp: false,
  crawlingComp: false,
  sittingComp: false,
  crawlingOnHandAndKneesComp: false,
  pullingUpToStandComp: false,
  cruisingComp: false,
  standingComp: false,
  walkingComp: false,
});
